Migrate static metadata to `pyproject.toml`
eduMFA/eduMFA pull request #218
Opened 2024-07-18 09:57 UTC by Luc1412

While the setup.py isn't deprecated for configuring a project, a `pyproject.toml` is the recommended way to do so.

This pull request is the first attempt on modernizing the project, by moving all static data into the `pyproject.toml`.

2024-07-19 04:23 UTC, fritterhoff commented
Great! Thanks for the attempt. I am not sure if we will get rid of the old setup.cfg since the used `data_files` has no version in pyproject.toml ...

2024-07-19 07:40 UTC, Luc1412 commented
> Great! Thanks for the attempt. I am not sure if we will get rid of the old setup.cfg since the used `data_files` has no version in pyproject.toml ...

The focus is more on static metadata. Having a setup.py is neither deprecated nor an issue.

2024-07-27 08:56 UTC, fritterhoff requested changes
Looks good so far. Beside the version in the url I think we can merge it next week? :)

2024-07-27 08:56 UTC, fritterhoff commented on pyproject.toml
> +Documentation = "https://edumfa.readthedocs.io/en/v2.1.0/"
Maybe we can change that to a more generic link so we don't have to update it everytime?

2024-07-29 09:04 UTC, fritterhoff approved these changes

2024-07-29 09:04 UTC, merged