Add support for Ubuntu 24.04LTS images
eduMFA/eduMFA pull request #290
Opened 2024-08-23 12:54 UTC by Luc1412

This pull request adds support for automatically building Ubuntu 22.04LTS images.

2024-08-24 04:41 UTC, fritterhoff requested changes

2024-08-24 04:41 UTC, fritterhoff commented on .github/workflows/ubuntu.yml
> +    runs-on: ubuntu-24.04 [Beta]
I think that should be named `runs-on: ubuntu-24.04` (without `[Beta]`)

2024-08-26 08:01 UTC, Luc1412 commented
I keep this PR on hold, while we resolve issues with our apt repository

2024-09-25 11:14 UTC, j-hoff approved these changes
looks good

2024-09-27 17:10 UTC, fritterhoff approved these changes

2024-09-27 17:10 UTC, merged